### ISSUE TITLE
[Occurrence] Draft causing duplicate members

### ISSUE THREAD

**Issue by JeffreyYHWang** [josephj/rollcall#21]
Some members are duplicated. For example, Jeffrey Wang in Song of Songs B.

**Comment by josephj** [comment]
@JeffreyYHWang 

It's because the API also lists the draft (unpublished) one as a separated entry. I will need to find a way to exclude it.

![CleanShot 2023-08-17 at 05 36 21@2x](https://github.com/josephj/rollcall/assets/136648/0ded5bcb-9ec4-4ed1-99e5-7138987d0b58)

![CleanShot 2023-08-17 at 05 34 34@2x](https://github.com/josephj/rollcall/assets/136648/a3a8f05c-5a20-453d-981c-17bb53be0068)

**Comment by josephj** [comment]
@JeffreyYHWang Now the draft ones should be excluded. Feel free to reopen this ticket if it still happens to you. 

![CleanShot 2023-08-17 at 06 19 06@2x](https://github.com/josephj/rollcall/assets/136648/dbca6993-fc96-442d-860f-90544ee29c1f)
